services:
  postgres:
    build:
      context: ./postgres
    container_name: prsk-postgres
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    working_dir: /home/postgres
    ports:
      - "15432:5432"
    tty: true
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: prsk_lab_dev
